ucb-substrate/substrate2

- docs/substrate/docs/development/_category_.json
- docs/substrate/docs/development/getting-started.md
- docs/substrate/src/css/custom.css
- feat(docs): add developer docs
- feat(dev-docs): add dev getting started guide
> feat(dev-docs): add developer getting started guide

- geometry/src/align.rs
- geometry/src/intersect.rs
- geometry/src/lib.rs
- geometry/src/point.rs
- geometry/src/prelude.rs
- geometry/src/rect.rs
- geometry/src/span.rs
- geometry/src/transform.rs
- geometry/src/union.rs
fix(geometry-traits): make default traits take in a mutable pointer
> feat(alignment-api): initial implementation of alignment API

- Cargo.lock
- geometry/Cargo.toml
- geometry/src/align.rs
- geometry/src/bbox.rs
- geometry/src/orientation.rs
- geometry/src/point.rs
- geometry/src/rect.rs
- geometry/src/span.rs
- geometry/src/transform.rs
- geometry/src/union.rs
feat(bounding-union): implemented `BoundingUnion` trait
> feat(trait-impls): implement traits for tuples, vecs

- Cargo.lock
- substrate-api/Cargo.toml
- substrate-api/src/block.rs
- substrate-api/src/lib.rs
- substrate-api/src/simulation/mod.rs
feat(simulation): support tuples of simulation analyses
> feat(simulation): initial simulator API

- Cargo.lock
- scir/src/lib.rs
- substrate-api/Cargo.toml
- substrate-api/src/context.rs
- substrate-api/src/io/impls.rs
- substrate-api/src/schematic/conv.rs
- substrate-api/src/schematic/mod.rs
- tests/src/substrate/block/mod.rs
- tests/src/substrate/block/schematic.rs
- feat(schematics): export Substrate schematics to SCIR
- fix lint issues
> feat(schematics): export Substrate schematics to SCIR

- .github/workflows/ci.yml
Build (but do not deploy) the documentation in the CI workflow
that runs on pull requests.
> feat(ci): check that the documentation site builds in CI

- substrate-api/src/schematic/mod.rs
- tests/src/substrate/block/schematic/internal_signal.rs
fix(tests): use into instead of explicit InOut wrapper
fix(tests): remove unused import
> fix(tests): use into instead of explicit InOut wrapper

- Cargo.lock
- substrate-api/src/context.rs
- substrate-api/src/schematic/mod.rs
- substrate-api/src/simulation/mod.rs
- substrate/src/ios.rs
- tests/src/shared/vdivider/tb.rs
- tools/spectre/Cargo.toml
- tools/spectre/src/blocks.rs
- tools/spectre/src/lib.rs
- tools/spectre/src/netlist.rs
feat(spectre): create Spectre DC vsource block
> feat(simulation): testbench schematic components

- Cargo.lock
- substrate-api/Cargo.toml
- substrate-api/src/simulation/mod.rs
- substrate-api/src/simulation/waveform.rs
feat(waveforms): clocked digital waveform builder
feat(waveforms): edge and transition APIs
feat(waveforms): implement Waveform and WaveformRef
> feat(waveforms): time-domain waveform API

- .github/workflows/check-workspace.yml
- .github/workflows/coverage.yml
- codegen/src/io.rs
- libs/cache/src/client.rs
fix(codegen): remove todo comment
> fix(tests): increase cache server wait time

- codegen/src/block/schematic.rs
- docs/examples/examples/core.rs
- pdks/sky130pdk/src/lib.rs
- substrate/src/context.rs
- substrate/src/simulation/mod.rs
- tests/src/gds.rs
- tests/src/hard_macro.rs
- tests/src/layout.rs
- tests/src/pdk.rs
- tests/src/shared/buffer/layout.rs
- tests/src/shared/inverter/tb.rs
- tests/src/sim/spectre.rs
> feat(pdk): remove `PdkData` object to clean up interface

- libs/scir/src/lib.rs
- libs/spice/src/parser/conv.rs
- libs/spice/src/parser/mod.rs
- tests/data/spice/buffer.spice
- tests/data/spice/inverter.spice
- tests/data/spice/inverter2.spice
- tests/data/spice/res_100.spice
- tests/data/spice/res_200.spice
- tests/data/spice/vdivider_duplicate_subckt.spice
- tests/src/hard_macro.rs
- tests/src/shared/vdivider/mod.rs
- tests/src/shared/vdivider/tb.rs
- tests/src/sim/spectre.rs
- feat(spice-parser): spice parser can follow include directives
- fix: update hard macro test
> feat(spice-parser): spice parser follows include directives

- libs/scir/src/lib.rs
- substrate/src/schematic/conv.rs
- substrate/src/schematic/mod.rs
- substrate/src/schematic/primitives.rs
- tests/src/schematic.rs
- tests/src/shared/vdivider/flattened.rs
- tests/src/shared/vdivider/mod.rs
- tests/src/shared/vdivider/tb.rs
- tests/src/sim/spectre.rs
feat(primitives): add built-in resistor and capacitor schematic blocks
> feat(primitives): add 2-terminal capacitor primitive

- docs/site/docs/introduction/inverter.md
- examples/Cargo.lock
- examples/sky130_inverter/Cargo.toml
- examples/sky130_inverter/src/lib.rs
- examples/sky130_inverter/src/tb.rs
- chore(examples): bump substrate version in examples
- update docs
> chore(examples): update examples to substrate v0.6.1

- .release-please-manifest.json
- Cargo.lock
- Cargo.toml
- libs/enumify/Cargo.toml
- libs/enumify/src/lib.rs
- libs/enumify_macros/Cargo.toml
- libs/enumify_macros/src/impls.rs
- libs/enumify_macros/src/lib.rs
- libs/opacity/Cargo.toml
- libs/opacity/src/lib.rs
- release-please-config.json
- work on enumify
- implement as ref and as mut
- fix lint
> feat(codegen): enumify attribute macro

- libs/atoll/src/abs.rs
- libs/atoll/src/grid.rs
- libs/atoll/src/lib.rs
- libs/atoll/src/route.rs
- tests/src/atoll/mod.rs
- fix warnings, start working on abstract merging
- basic routing api
> routing api

- substrate/src/simulation/waveform.rs
- tools/spectre/src/blocks.rs
Waveforms are now generic over their datatype.
This allows using `f64`, `Decimal`, or other numeric types
as the storage format of a waveform.
> feat(waveform): support generic waveform datatypes

- libs/atoll/src/abs.rs
- libs/atoll/src/lib.rs
- substrate/src/io/layout.rs
- feat(layout): add `Bbox` implementation for `PortGeometry`
- fix(atoll): Fix how ATOLL creates/uses abstracts
> fix(atoll): fix how ATOLL creates/uses abstracts

- tests/src/sim/sky130.rs
- tools/spectre/src/lib.rs
- **montecarlo tests checks number of runs**
- **clean up montecarlo impl**
- **rename and2 test to identify use of monte carlo**
> fix(spectre): make monte carlo return vec of analysis outputs

- Cargo.lock
- libs/atoll/Cargo.toml
- libs/atoll/src/abs.rs
- libs/atoll/src/lib.rs
- libs/atoll/src/route.rs
- substrate/src/io/layout.rs
- substrate/src/layout/element.rs
- substrate/src/layout/gds.rs
- tests/src/atoll/mod.rs
- **fix(gds): fix GDS unit checks during import**
- **feat(atoll): API for blocking available points on layer**
> fix(atoll): abstract/autorouter fixes and APIs

- tools/spectre/src/lib.rs
This allows users to use Spectre options to globally
set the list of saved signals. This is useful if users
want to save all public signals, rather than explicitly
saving each one.
> feat(spectre): allow setting global save option

- libs/scir/src/lib.rs
- libs/spice/src/netlist.rs
- substrate/src/schematic/conv.rs
- **feat(scir): expose port directions, update docs**
- **expose conversion cell ID lookup**
> feat(scir): expose port directions, update docs

- Cargo.lock
- libs/verilog/src/lib.rs
- **feat(verilog): export all verilog shells**
- **escape verilog identifiers**
- **add comma to set of chars triggering verilog escape**
> feat(verilog): support exporting all cells

- libs/atoll/src/straps.rs
- libs/spice/src/lib.rs
- libs/spice/src/netlist.rs
- libs/spice/src/parser/conv.rs
- libs/spice/src/parser/mod.rs
- libs/spice/src/parser/shorts.rs
- **feat(straps): cut power straps to vias**
- **fix(cdl): handle slashes while parsing instances**
- **add support for BJTs**
- **finish adding support for BJTs**
> feat(bjt): add support for BJTs

- tools/spectre/src/lib.rs
Users can set Spectre flags using the Spectre `Options` struct.
> feat(spectre): allow overriding spectre flags

- codegen/src/io.rs
- substrate/src/types/impls.rs
- substrate/src/types/mod.rs
- substrate/src/types/schematic.rs
- **Modify traits to allow simplified codegen**
- **finish basic codegen**
> fix(codegen): update codegen to use fewer structs

- Cargo.lock
- examples/latest/sky130_inverter/Cargo.toml
- examples/latest/sky130_inverter/src/layout.rs
- pdks/sky130pdk/src/mos.rs
- tools/magic-netgen/src/lib.rs
- **run lvs on sky130 inverter**
- **make tiles magic compatible**
> feat(tutorial): run LVS on SKY130 inverter example

- tools/magic/src/drc.rs
- tools/magic/src/utils.rs
- tools/magic/templates/drc.tcl
- **fix magic drc**
- **typo**
- **use stdin = null, improve test assertion**
> fix(drc): fix bugs in Magic DRC plugin

- Cargo.lock
- examples/latest/sky130_inverter/Cargo.toml
- examples/latest/sky130_inverter/src/layout.rs
- pdks/sky130pdk/src/mos.rs
- tools/magic/src/drc.rs
- tools/magic/src/extract.rs
- tools/magic/src/pex.rs
- tools/magic/src/utils.rs
- tools/magic/templates/drc.tcl
- **feat(tutorial): run Magic DRC for open-source sky130 inverter tutorial**
- **fix lints**
- **magic ensure drc complete**
- **fix licon.8 drc error**
> feat(tutorial): run Magic DRC, fix licon.8 DRC error

- .release-please-manifest.json
- Cargo.lock
- Cargo.toml
- bins/spicemerge/Cargo.toml
- bins/spicemerge/src/main.rs
- libs/spice/src/parser/mod.rs
- release-please-config.json
- **feat(spicemerge): add command line tool for aggregating SPICE netlists**
- **debug print dialect**
> feat(spicemerge): add command line tool for aggregating SPICE netlists

- examples/latest/colbuf/Cargo.toml
- examples/latest/vdivider/Cargo.toml
- substrate/src/types/impls.rs
- tools/magic/Cargo.toml
`Output<T>` and `InOut<T>` now flatten to the correct directions.
> fix(schematic): fix bug in direction wrapper type flattening

- Cargo.lock
- examples/latest/sky130_inverter/Cargo.toml
- examples/latest/sky130_inverter/src/atoll/mod.rs
- libs/atoll/src/fold.rs
- pdks/sky130/src/atoll.rs
- **try to fix inverter chain example**
- **finish minimal inverter chain example**
> feat(atoll): add inverter chain folding example
